[package]
name = "bubbletea"
version = "0.1.0"
edition = "2024"

# cargo build --release
[profile.release]
opt-level = 3
debug = false
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 1
rpath = false

[dependencies]
